#!/bin/sh

picom &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d web term code chat music 6 7 

bspc config border_width         5
bspc config window_gap           37 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color    "#88C0D0"
bspc config normal_border_color     "#3B4252"

xsetroot -cursor_name left_ptr &
feh --bg-fill --no-fehbg ~/wallpapers/current.jpg &
polybar top &