#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

external=$(xrandr --query | grep 'DisplayPort-0')
if echo $external | grep -q ' connected'; then
    xrandr --fb 6240x3510 \
        --output eDP --mode 1920x1080 --scale 1.25x1.25 --panning 2400x1350+0+0 \
        --output DisplayPort-0 --mode 3840x2160 --pos 2400x0

    bspc monitor eDP -d 1 2 3 4 5
    bspc monitor DisplayPort-0 -d 6 7 8 9 10

    polybar top_internal &
    polybar top_external &
else
    xrandr --fb 2400x1350 \
        --output eDP --mode 1920x1080 --scale 1.25x1.25 --panning 2400x1350+0+0 \
        --output HDMI-A-0 --off

    bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10

    polybar top_internal &
fi

picom --config ~/.config/picom.conf &

bspc config border_width         12
bspc config window_gap           22

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color    "#586e75"
bspc config normal_border_color     "#002b36"

wmname LG3D &
xsetroot -cursor_name left_ptr &
feh --bg-fill --no-fehbg ~/wallpapers/current_internal.jpg ~/wallpapers/current_external.jpg &
