add_newline = true
command_timeout = 750

format = """
$directory\
$git_status\
$git_branch\
$kubernetes\
$line_break\
$character
"""

[git_branch]
format = " [ $branch]($style) "

[kubernetes]
disabled = false
format = '[ 󱃾  $context ]($style) '
