#!/usr/bin/env bash

TARGET=$(fd -t d --exact-depth 1 . $HOME/Development/personal |
  sed "s~$HOME/~~" |
  fzf --prompt "project > ")

TAB_NAME=$(echo $TARGET)
kitty @ focus-tab --match title:$TAB_NAME 2>/dev/null || kitty @ launch --type tab --tab-title $TAB_NAME $TARGET
