#!/usr/bin/env bash

TARGET=$(fd -t d --exact-depth 1 . $HOME/Development/personal $HOME/Development/work |
	sed "s~$HOME/Development/~~" |
	fzf --prompt "project > ")

wezterm cli spawn --cwd $HOME/$TARGET
