[General]
background=assets/login.jpg

ScreenWidth=1980
ScreenHeight=1080

blur=true
recursiveBlurLoops=2
recursiveBlurRadius=15

PasswordFieldOutlined=true

PowerIconSize=
FontPointSize=
AvatarPixelSize=

translationReboot=
translationSuspend=
translationPowerOff=